theme: minima

plugins:
  - jekyll-titles-from-headings

titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true 

title: League of legends top lane impact analysis
author:
  Marco Sanchez
  mas023@ucsd.edu

header_pages:
  Marco Sanchez

description: >
  Analysis on whether having a top laner ahead in gold 
  15 minutes into the game makes winning the game more likely.


