theme: minima

plugins:
  - jekyll-titles-from-headings

titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true 

title: League of Legends win/loss prediction
author:
  Marco Sanchez
  mas023@ucsd.edu

header_pages:
  Marco Sanchez

description: >
  Prediction model trained to predict 
  whether a team won or lost in a game 
  of League of Legends.


